export default {
    Vanilla: require('../../assets/images/vanilla.png'),
    Coconut: require('../../assets/images/coconut.png'),
    Chocolate: require('../../assets/images/chocolate.png'),
    'Green Tea': require('../../assets/images/green_tea.png'),
    'Black Sesame': require('../../assets/images/black_sesame.png'),
    'Ripple Blueberry': require('../../assets/images/blueberry.png'),
    'Chip Chocolate': require('../../assets/images/chocolate_chip.png'),
    'Ripple Chocolate': require('../../assets/images/chocolate_ripple.png'),
    'Cream Cookies': require('../../assets/images/cookies.png'),
    'Double Chocolate': require('../../assets/images/double_chocolate.png'),
    Durian: require('../../assets/images/durian.png'),
    Jackfruit: require('../../assets/images/jack_fruit.png'),
    'Lemon Sherbet': require('../../assets/images/lemon.png'),
    'Lychee Sherbet': require('../../assets/images/lychee.png'),
    Mango: require('../../assets/images/mango.png'),
    Milk: require('../../assets/images/milk.png'),
    'Mint Chocolate': require('../../assets/images/mint_chocolate.png'),
    Mocha: require('../../assets/images/mocha.png'),
    'Mocha Chip': require('../../assets/images/mocha_chip.png'),
    Pandan: require('../../assets/images/pandan.png'),
    'Passion Fruit': require('../../assets/images/passion.png'),
    'Swirl Raspberry': require('../../assets/images/raspberry.png'),
    'Raisin Grandeur': require('../../assets/images/raisin.png'),
    'Salted Camarel': require('../../assets/images/salted_camarel.png'),
    Strawberry: require('../../assets/images/strawberry.png'),
    'Sweet Corn': require('../../assets/images/corn.png'),
    Taro: require('../../assets/images/taro.png'),
    'Milk Tea': require('../../assets/images/milk_tea.png'),
    Tropicana: require('../../assets/images/tropicana.png'),
    'Tuiti Fruity': require('../../assets/images/tuiti.png'),
    Yogurt: require('../../assets/images/yogurt.png'),
    Yuzu: require('../../assets/images/yuzu.png')
};
